apiVersion: apps/v1

kind: Deployment

metadata:

  name: my-deployment
  namespace: dev.1.o
  label:
    app: my-app
  environment: dev

spec:

  selector:

    matchLabels:

      app: my-app

  replicas: 3

  template:

    metadata:
      namespace: dev.1.o

      labels:

        app: my-app
      
      environment: dev

    spec:
      containers:

      - name: my-app

      image: nginx:latest 

      ports:

        - containerPort: 80

      
